//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elenora {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsRO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsRO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("elenora.StringsRO", typeof(StringsRO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxÁsványkarkötő tervezőxx.
        /// </summary>
        public static string Ásványkarkötő_tervező {
            get {
                return ResourceManager.GetString("Ásványkarkötő tervező", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxÁsványok szerintxx.
        /// </summary>
        public static string Ásványok_szerint {
            get {
                return ResourceManager.GetString("Ásványok szerint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxFérfixx.
        /// </summary>
        public static string Férfi {
            get {
                return ResourceManager.GetString("Férfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxFérfi karkötőkxx.
        /// </summary>
        public static string Férfi_karkötők {
            get {
                return ResourceManager.GetString("Férfi karkötők", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxHoroszkópxx.
        /// </summary>
        public static string Horoszkóp {
            get {
                return ResourceManager.GetString("Horoszkóp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxHoroszkóp karkötőkxx.
        /// </summary>
        public static string Horoszkóp_karkötők {
            get {
                return ResourceManager.GetString("Horoszkóp karkötők", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxKészletenxx.
        /// </summary>
        public static string Készleten {
            get {
                return ResourceManager.GetString("Készleten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxKosásxx.
        /// </summary>
        public static string Kosár {
            get {
                return ResourceManager.GetString("Kosár", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxKosárba teszemxx.
        /// </summary>
        public static string Kosárba_teszem {
            get {
                return ResourceManager.GetString("Kosárba teszem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxKötöttxx.
        /// </summary>
        public static string Kötött {
            get {
                return ResourceManager.GetString("Kötött", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxKötött karkötő tervezőxx.
        /// </summary>
        public static string Kötött_karkötő_tervező {
            get {
                return ResourceManager.GetString("Kötött karkötő tervező", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxNőixx.
        /// </summary>
        public static string Női {
            get {
                return ResourceManager.GetString("Női", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxNői karkötőkxx.
        /// </summary>
        public static string Női_karkötők {
            get {
                return ResourceManager.GetString("Női karkötők", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxPárosxx.
        /// </summary>
        public static string Páros {
            get {
                return ResourceManager.GetString("Páros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxPáros karkötőkxx.
        /// </summary>
        public static string Páros_karkötők {
            get {
                return ResourceManager.GetString("Páros karkötők", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xxPénztárxx.
        /// </summary>
        public static string Pénztár {
            get {
                return ResourceManager.GetString("Pénztár", resourceCulture);
            }
        }
    }
}
