//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elenora {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("elenora.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ásványkarkötő tervező.
        /// </summary>
        public static string Ásványkarkötő_tervező {
            get {
                return ResourceManager.GetString("Ásványkarkötő tervező", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ásványok szerint.
        /// </summary>
        public static string Ásványok_szerint {
            get {
                return ResourceManager.GetString("Ásványok szerint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itt van pár példa karkötő amit mások készítettek:.
        /// </summary>
        public static string CBD_V2_EXAMPLE_IMAGES {
            get {
                return ResourceManager.GetString("CBD_V2_EXAMPLE_IMAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szia!.
        /// </summary>
        public static string CBD_V2_SALUTATION {
            get {
                return ResourceManager.GetString("CBD_V2_SALUTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tervező lépésről lépésre végig visz a folyamaton. Kezdjünk is bele!.
        /// </summary>
        public static string CBD_V2_START_DESCRIPTION {
            get {
                return ResourceManager.GetString("CBD_V2_START_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Négy alap karkötő stílusból lehet kiindúlni, csak egy fajta ásvánnyal, vagy kér ásvánnyal váltogatva:.
        /// </summary>
        public static string CBD_V2_START_STYLES_DESCRIPTION {
            get {
                return ResourceManager.GetString("CBD_V2_START_STYLES_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Válassz egy stílust!.
        /// </summary>
        public static string CBD_V2_START_STYLES_DESCRIPTION_CHOOSE {
            get {
                return ResourceManager.GetString("CBD_V2_START_STYLES_DESCRIPTION_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próbáld ki a karkötő tervezőnket és készíts személyre szabott, feliratos karkötőt, amely tökéletes ajándék lehet bármilyen alkalomra!.
        /// </summary>
        public static string CBD_V2_WELCOME {
            get {
                return ResourceManager.GetString("CBD_V2_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha mégsem tetszene, akkor 30 napos visszafizetési garanciát vállalunk!.
        /// </summary>
        public static string CBD_V2_WELCOME2 {
            get {
                return ResourceManager.GetString("CBD_V2_WELCOME2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Férfi.
        /// </summary>
        public static string Férfi {
            get {
                return ResourceManager.GetString("Férfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Férfi karkötők.
        /// </summary>
        public static string Férfi_karkötők {
            get {
                return ResourceManager.GetString("Férfi karkötők", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horoszkóp.
        /// </summary>
        public static string Horoszkóp {
            get {
                return ResourceManager.GetString("Horoszkóp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horoszkóp karkötők.
        /// </summary>
        public static string Horoszkóp_karkötők {
            get {
                return ResourceManager.GetString("Horoszkóp karkötők", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Készleten.
        /// </summary>
        public static string Készleten {
            get {
                return ResourceManager.GetString("Készleten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosár.
        /// </summary>
        public static string Kosár {
            get {
                return ResourceManager.GetString("Kosár", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosárba.
        /// </summary>
        public static string Kosárba_teszem {
            get {
                return ResourceManager.GetString("Kosárba teszem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kötött.
        /// </summary>
        public static string Kötött {
            get {
                return ResourceManager.GetString("Kötött", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kötött karkötő tervező.
        /// </summary>
        public static string Kötött_karkötő_tervező {
            get {
                return ResourceManager.GetString("Kötött karkötő tervező", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Női.
        /// </summary>
        public static string Női {
            get {
                return ResourceManager.GetString("Női", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Női karkötők.
        /// </summary>
        public static string Női_karkötők {
            get {
                return ResourceManager.GetString("Női karkötők", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Páros.
        /// </summary>
        public static string Páros {
            get {
                return ResourceManager.GetString("Páros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Páros karkötők.
        /// </summary>
        public static string Páros_karkötők {
            get {
                return ResourceManager.GetString("Páros karkötők", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pénztár.
        /// </summary>
        public static string Pénztár {
            get {
                return ResourceManager.GetString("Pénztár", resourceCulture);
            }
        }
    }
}
