services:
  elenora:
    container_name: elenora
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - 5008:80
    volumes:
      - ${PWD}/logs:/logs
      - ${PWD}/elenora-wwwroot:/app/wwwroot

  database:
    image: postgres:latest
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: elenora
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data