Resources:

  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: elenora-ecr-repository
  
  DatabaseCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: elenoradb
      Engine: aurora-postgresql
      EngineMode: serverless
      MasterUsername: admin